=== zandmd/esp32-projects/eda/gen/ESP32-WROOM-32E-N4/datasheet.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="datasheet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="io-mux">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="io" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="gpio" type="xs:int" />
                                        <xs:element name="pad-name" type="xs:string" />
                                        <xs:element name="func-0" type="xs:string" />
                                        <xs:element name="func-1" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="func-2" type="xs:string" />
                                        <xs:element name="func-3" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="func-4" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="func-5" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="reset">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="0" />
                                                    <xs:enumeration value="1" />
                                                    <xs:enumeration value="2" />
                                                    <xs:enumeration value="3" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="notes" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="R" />
                                                    <xs:enumeration value="R,I" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rtc-mux">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="io" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="rtc-gpio-num" type="xs:int" />
                                        <xs:element name="gpio-num" type="xs:int" />
                                        <xs:element name="pad-name" type="xs:string" />
                                        <xs:element name="analog-0" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="analog-1" type="xs:string" />
                                        <xs:element name="analog-2" minOccurs="0" maxOccurs="1" type="xs:string" />
                                        <xs:element name="rtc-0" type="xs:string" />
                                        <xs:element name="rtc-1" minOccurs="0" maxOccurs="1" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="spi-pins">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="config" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="pin" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="spi" type="xs:string" />
                                                    <xs:element name="hspi" type="xs:string" />
                                                    <xs:element name="vspi" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="name" type="xs:string" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="bootloader">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pull-down" type="xs:int" minOccurs="1" maxOccurs="unbounded" />
                            <xs:element name="pull-up" type="xs:int" minOccurs="1" maxOccurs="unbounded" />
                            <xs:element name="pwm" type="xs:int" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="module">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="no-connect" type="xs:int" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="physical">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="gpio" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="pin" type="xs:int" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== zandmd/esp32-projects/eda/gen/ESP32-WROOM-32E-N4/datasheet.xml
<?xml version="1.0" encoding="utf-8"?>
<datasheet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datasheet.xsd">
    <!-- https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf -->
    <!-- 4.10 IO_MUX Pad List -->
    <io-mux>
        <io>
            <gpio>0</gpio>
            <pad-name>GPIO0</pad-name>
            <func-0>GPIO0</func-0>
            <func-1>CLK_OUT1</func-1>
            <func-2>GPIO0</func-2>
            <func-5>EMAC_TX_CLK</func-5>
            <reset>3</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>1</gpio>
            <pad-name>U0TXD</pad-name>
            <func-0>U0TXD</func-0>
            <func-1>CLK_OUT3</func-1>
            <func-2>GPIO1</func-2>
            <func-5>EMAC_RXD2</func-5>
            <reset>3</reset>
        </io>
        <io>
            <gpio>2</gpio>
            <pad-name>GPIO2</pad-name>
            <func-0>GPIO2</func-0>
            <func-1>HSPIWP</func-1>
            <func-2>GPIO2</func-2>
            <func-3>HS2_DATA0</func-3>
            <func-4>SD_DATA0</func-4>
            <reset>2</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>3</gpio>
            <pad-name>U0RXD</pad-name>
            <func-0>U0RXD</func-0>
            <func-1>CLK_OUT2</func-1>
            <func-2>GPIO3</func-2>
            <reset>3</reset>
        </io>
        <io>
            <gpio>4</gpio>
            <pad-name>GPIO4</pad-name>
            <func-0>GPIO4</func-0>
            <func-1>HSPIHD</func-1>
            <func-2>GPIO4</func-2>
            <func-3>HS2_DATA1</func-3>
            <func-4>SD_DATA1</func-4>
            <func-5>EMAC_TX_ER</func-5>
            <reset>2</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>5</gpio>
            <pad-name>GPIO5</pad-name>
            <func-0>GPIO5</func-0>
            <func-1>VSPICS0</func-1>
            <func-2>GPIO5</func-2>
            <func-3>HS1_DATA6</func-3>
            <func-5>EMAC_RX_CLK</func-5>
            <reset>3</reset>
        </io>
        <io>
            <gpio>6</gpio>
            <pad-name>SD_CLK</pad-name>
            <func-0>SD_CLK</func-0>
            <func-1>SPICLK</func-1>
            <func-2>GPIO6</func-2>
            <func-3>HS1_CLK</func-3>
            <func-4>U1CTS</func-4>
            <reset>3</reset>
        </io>
        <io>
            <gpio>7</gpio>
            <pad-name>SD_DATA_0</pad-name>
            <func-0>SD_DATA0</func-0>
            <func-1>SPIQ</func-1>
            <func-2>GPIO7</func-2>
            <func-3>HS1_DATA0</func-3>
            <func-4>U2RTS</func-4>
            <reset>3</reset>
        </io>
        <io>
            <gpio>8</gpio>
            <pad-name>SD_DATA_1</pad-name>
            <func-0>SD_DATA1</func-0>
            <func-1>SPID</func-1>
            <func-2>GPIO8</func-2>
            <func-3>HS1_DATA1</func-3>
            <func-4>U2CTS</func-4>
            <reset>3</reset>
        </io>
        <io>
            <gpio>9</gpio>
            <pad-name>SD_DATA_2</pad-name>
            <func-0>SD_DATA2</func-0>
            <func-1>SPIHD</func-1>
            <func-2>GPIO9</func-2>
            <func-3>HS1_DATA2</func-3>
            <func-4>U1RXD</func-4>
            <reset>3</reset>
        </io>
        <io>
            <gpio>10</gpio>
            <pad-name>SD_DATA_3</pad-name>
            <func-0>SD_DATA3</func-0>
            <func-1>SPIWP</func-1>
            <func-2>GPIO10</func-2>
            <func-3>HS1_DATA3</func-3>
            <func-4>U1TXD</func-4>
            <reset>3</reset>
        </io>
        <io>
            <gpio>11</gpio>
            <pad-name>SD_CMD</pad-name>
            <func-0>SD_CMD</func-0>
            <func-1>SPICS0</func-1>
            <func-2>GPIO11</func-2>
            <func-3>HS1_CMD</func-3>
            <func-4>U1RTS</func-4>
            <reset>3</reset>
        </io>
        <io>
            <gpio>12</gpio>
            <pad-name>MTDI</pad-name>
            <func-0>MTDI</func-0>
            <func-1>HSPIQ</func-1>
            <func-2>GPIO12</func-2>
            <func-3>HS2_DATA2</func-3>
            <func-4>SD_DATA2</func-4>
            <func-5>EMAC_TXD3</func-5>
            <reset>2</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>13</gpio>
            <pad-name>MTCK</pad-name>
            <func-0>MTCK</func-0>
            <func-1>HSPID</func-1>
            <func-2>GPIO13</func-2>
            <func-3>HS2_DATA3</func-3>
            <func-4>SD_DATA3</func-4>
            <func-5>EMAC_RX_ER</func-5>
            <reset>2</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>14</gpio>
            <pad-name>MTMS</pad-name>
            <func-0>MTMS</func-0>
            <func-1>HSPICLK</func-1>
            <func-2>GPIO14</func-2>
            <func-3>HS2_CLK</func-3>
            <func-4>SD_CLK</func-4>
            <func-5>EMAC_TXD2</func-5>
            <reset>3</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>15</gpio>
            <pad-name>MTDO</pad-name>
            <func-0>MTDO</func-0>
            <func-1>HSPICS0</func-1>
            <func-2>GPIO15</func-2>
            <func-3>HS2_CMD</func-3>
            <func-4>SD_CMD</func-4>
            <func-5>EMAC_RXD3</func-5>
            <reset>3</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>16</gpio>
            <pad-name>GPIO16</pad-name>
            <func-0>GPIO16</func-0>
            <func-2>GPIO16</func-2>
            <func-3>HS1_DATA4</func-3>
            <func-4>U2RXD</func-4>
            <func-5>EMAC_CLK_OUT</func-5>
            <reset>1</reset>
        </io>
        <io>
            <gpio>17</gpio>
            <pad-name>GPIO17</pad-name>
            <func-0>GPIO17</func-0>
            <func-2>GPIO17</func-2>
            <func-3>HS1_DATA5</func-3>
            <func-4>U2TXD</func-4>
            <func-5>EMAC_CLK_180</func-5>
            <reset>1</reset>
        </io>
        <io>
            <gpio>18</gpio>
            <pad-name>GPIO18</pad-name>
            <func-0>GPIO18</func-0>
            <func-1>VSPICLK</func-1>
            <func-2>GPIO18</func-2>
            <func-3>HS1_DATA7</func-3>
            <reset>1</reset>
        </io>
        <io>
            <gpio>19</gpio>
            <pad-name>GPIO19</pad-name>
            <func-0>GPIO19</func-0>
            <func-1>VSPIQ</func-1>
            <func-2>GPIO19</func-2>
            <func-3>U0CTS</func-3>
            <func-4>EMAC_TXD0</func-4>
            <reset>1</reset>
        </io>
        <io>
            <gpio>21</gpio>
            <pad-name>GPIO21</pad-name>
            <func-0>GPIO21</func-0>
            <func-1>VSPIHD</func-1>
            <func-2>GPIO21</func-2>
            <func-5>EMAC_TX_EN</func-5>
            <reset>1</reset>
        </io>
        <io>
            <gpio>22</gpio>
            <pad-name>GPIO22</pad-name>
            <func-0>GPIO22</func-0>
            <func-1>VSPIWP</func-1>
            <func-2>GPIO22</func-2>
            <func-3>U0RTS</func-3>
            <func-5>EMAC_TXD1</func-5>
            <reset>1</reset>
        </io>
        <io>
            <gpio>23</gpio>
            <pad-name>GPIO23</pad-name>
            <func-0>GPIO23</func-0>
            <func-1>VSPID</func-1>
            <func-2>GPIO23</func-2>
            <func-3>HS1_STROBE</func-3>
            <reset>1</reset>
        </io>
        <io>
            <gpio>25</gpio>
            <pad-name>GPIO25</pad-name>
            <func-0>GPIO25</func-0>
            <func-2>GPIO25</func-2>
            <func-5>EMAC_RXD0</func-5>
            <reset>0</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>26</gpio>
            <pad-name>GPIO26</pad-name>
            <func-0>GPIO26</func-0>
            <func-2>GPIO26</func-2>
            <func-5>EMAC_RXD1</func-5>
            <reset>0</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>27</gpio>
            <pad-name>GPIO27</pad-name>
            <func-0>GPIO27</func-0>
            <func-2>GPIO27</func-2>
            <func-5>EMAC_RX_DV</func-5>
            <reset>0</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>32</gpio>
            <pad-name>32K_XP</pad-name>
            <func-0>GPIO32</func-0>
            <func-2>GPIO32</func-2>
            <reset>0</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>33</gpio>
            <pad-name>32K_XN</pad-name>
            <func-0>GPIO33</func-0>
            <func-2>GPIO33</func-2>
            <reset>0</reset>
            <notes>R</notes>
        </io>
        <io>
            <gpio>34</gpio>
            <pad-name>VDET_1</pad-name>
            <func-0>GPIO34</func-0>
            <func-2>GPIO34</func-2>
            <reset>0</reset>
            <notes>R,I</notes>
        </io>
        <io>
            <gpio>25</gpio>
            <pad-name>VDET_2</pad-name>
            <func-0>GPIO35</func-0>
            <func-2>GPIO35</func-2>
            <reset>0</reset>
            <notes>R,I</notes>
        </io>
        <io>
            <gpio>36</gpio>
            <pad-name>SENSOR_VP</pad-name>
            <func-0>GPIO36</func-0>
            <func-2>GPIO36</func-2>
            <reset>0</reset>
            <notes>R,I</notes>
        </io>
        <io>
            <gpio>37</gpio>
            <pad-name>SENSOR_CAPP</pad-name>
            <func-0>GPIO37</func-0>
            <func-2>GPIO37</func-2>
            <reset>0</reset>
            <notes>R,I</notes>
        </io>
        <io>
            <gpio>38</gpio>
            <pad-name>SENSOR_CAPN</pad-name>
            <func-0>GPIO38</func-0>
            <func-2>GPIO38</func-2>
            <reset>0</reset>
            <notes>R,I</notes>
        </io>
        <io>
            <gpio>39</gpio>
            <pad-name>SENSOR_VN</pad-name>
